export * from './user.interface';
export * from './student.interface'
export * from './istaff'
export * from './ilogin-payload'
export * from './istudent-registration-payload'
export * from './istaff-registration-payload'
export * from './iforgot-password-payload'
export * from './ireset-password-payload'
export * from './iworkflow'
